### ISSUE TITLE
APKtoJava.exe now flagged as Malware 

### ISSUE THREAD

**Issue by jolibert** [broodplank/APKtoJava#9]
From various antivirus, yous file is reported as rootkit/Trojan, is there any explanations ?

https://www.virustotal.com/#/file/80c1e1d9be9fd2ab05db116b56490cdd3d8ae4a2446be60fb898a4c5a15af5aa/detection

**Comment by broodplank** [comment]
APKToJava is made in AutoIT,  AutoIT uses UPX to compress exe's. Some malware may be packed with UPX as well, so the anti virus thinks it's possible malware. ApkToJava is no malware and is even open source..
